### ISSUE TITLE
The First Person Camera look at the wrong direction in some animations.

### ISSUE THREAD

**Issue by osmelmc** [ArranzCNL/ImprovedCameraSE-NG#18] opened 2024-05-03 21:33 UTC
There are some animations that seems to rotate the actor skeleton interested of the actor in self.

In those animations the first person with this Mod still will look to the front of the actor from when the actor is really looking to another side (usually the opposite side)

IFPV also had this issue on it's first versions but eventually find the solution. Probably checking the Rotation of the NPC Node or the "MagicEffectNode" that is common for all the skeleton include the creature's.

**Comment by ArranzCNL** [comment] 2024-06-01 12:19
Hi sorry for the late response.

IFPV works completely differently just to set the record straight here it is Third Person only, it doesn't touch the first person camera at all it blocks you from entering it.

Now you state actor are you able to be more specific about this as I am assuming the issue is arising from non-humanoid actors in which case they have no functional head node implemented or something maybe like a chicken for example?

Would be awesome if you could give me an example of a creature which causes this problem. I'm changing the logic up in v2.0.1 so you will be able to latch the camera onto other "actors" which I currently have basically functionality implemented. Controlling them properly etc is beyond the remit of Improved Camera SE so I won't be fixing those issue(s), trying to get them into combat to swing there weapons or odd movement from certain creatures for example.

**Closed as completed** 2024-09-17 12:00 UTC
